### PR TITLE
fix: controllers/tc00004x tests

### LINKED ISSUE #904: fix controllers/tc00004x tests
- [x] controllers/tc000040_controlled_outputs_test.go
  - [x] controllers/tc000041_all_outputs_test.go
  - [x] controllers/tc000042_output_name_contains_dot_test.go
  - [x] controllers/tc000043_controlled_outputs_should_be_reconciled_test.go
  - [x] controllers/tc000044_plan_only_mode_test.go

### PR DESCRIPTION
**Pull request by yitsushi**
They passed constistently running them 3 times in a row without break, so no main suit cleanup.

```
❯ go test ./controllers -parallel 1 -count=3 -test.run Test_00004
ok      github.com/weaveworks/tf-controller/controllers 22.412s
```

Fixes #904

References:
* https://github.com/weaveworks/tf-controller/issues/904

### CODE REVIEW

File: controllers/tc000044_plan_only_mode_test.go [hunk 1]
```diff
@@ -128,11 +127,13 @@ func Test_000044_plan_only_mode_test(t *testing.T) {
 		}
 		return len(planOutput.Data), nil
 	}, timeout, interval).Should(Equal(1))
+	defer waitResourceToBeDelete(g, &planOutput)
 
 	By("checking that the output ConfigMap contains the correct output data, provisioned by the TF resource.")
 
 	g.Expect(planOutput.Name).To(Equal("tfplan-default-" + terraformName))
 	g.Expect(planOutput.Namespace).To(Equal("flux-system"))
+	fmt.Printf(" --- %s\n", createdHelloWorldTF.UID)
```
Comment (yiannistri) [inline controllers/tc000044_plan_only_mode_test.go:136]: Is this log line intentional?

Comment (yitsushi) [reply controllers/tc000044_plan_only_mode_test.go:136]: No it's not.

**Review by yiannistri — APPROVED** [review]
